### ISSUE TITLE
Add demo site

### ISSUE THREAD

**Issue by devomaa** [osmarks/nonlocality#1]

**Comment by osmarks** [comment]
I have one up at https://search.osmarks.tk/. Though it turns out that the search algorithms scale *awfully* to the large amount of data I fed in, so it's quite slow. If you have suggestions for that it would be helpful. I'm thinking about simplifying the search a lot, but it still needs to be able to favour stuff containing all the terms in a query somehow; it's quite hard, though I guess I could just use the built-in Postgres FTS.

**Comment by devomaa** [comment]
I see, it's awfully slow, This issue can be now closed.
